version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: docker_db1
      MYSQL_USER: pranilswami
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      s-network:

  app:
    build: .
    ports:
      - "8081:8081"
    networks:
      s-network:

volumes:
  mysql_data:

networks:
  s-network:
    driver: bridge
